FROM hexpm/elixir:1.11.3-erlang-23.2.1-debian-stretch-20201012

# install build dependencies
RUN apt-get update
RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y build-essential git nodejs

WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

ENV ENTRYKIT_VERSION 0.4.0

RUN curl --location --remote-name https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && mv entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && entrykit --symlink


ENTRYPOINT [ \
    "prehook", "elixir -v", "--", \
    "prehook", "mix deps.get", "--", \
    "prehook", "npm install --prefix assets", "--"]
